Paypal messaging feature update dependency
braintree/braintree_android pull request #1002
Opened 2024-05-14 19:36 UTC by warmkesselj

### Summary of changes

Update to use develop.3 for credit messaging and update the demo app to use the updated textAlignment property.

### Checklist

 - [ ] Added a changelog entry
 - [ ] Relevant test coverage

### Authors
@saperi22 
@KunJeongPark 
@jwarmkessel

2024-05-14 21:04 UTC, sarahkoop approved these changes

2024-05-14 21:05 UTC, sarahkoop requested changes
Didn't see the unit test failures before approving - requesting to fix those before approval

2024-05-15 13:48 UTC, sarahkoop commented on PayPalMessaging/build.gradle
> +    implementation('com.paypal.messages:paypal-messages:1.0.0-develop.3')
Just saw that this can now be 1.0.0 (no develop) - let's update that here

2024-05-15 17:43 UTC, sarahkoop approved these changes

2024-05-16 15:07 UTC, jaxdesmarais approved these changes

2024-05-16 17:55 UTC, merged